language: python
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get -y install python3-numpy python3-scipy python3-pip liblapack-dev libblas-dev gfortran
    - sudo pip3 install coverage codecov toolz parameterized codeclimate-test-reporter
    - sudo pip3 install setuptools numpy --upgrade
cache: pip
sudo: false
script: python3 setup.py test
dist: xenial
after_success:
    - codeclimate-test-reporter --token 71eb68ef3ba1f85d8e92407d03e43df51deb6f14a870ada23e8530a16d438eae
    - codecov --token=e3a3e622-b5b4-40a0-b0be-f427bbb23449
